default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 10

development:
  <<: *default
  database: turkish_spot

test:
  <<: *default

production:
  <<: *default
