default: &default
  adapter: postgresql
  encoding: unicode
  username: macos
  password: anvh
  pool: 5

development:
  <<: *default
  database: turkish_spot

test:
  <<: *default

production:
  <<: *default
